### ISSUE TITLE
Change rabbitMQ input plugin to be able to handle different messages

### ISSUE THREAD

**Issue by rsmith013** [cedadev/stac-generator#27]
At the moment it creates an `IngestMessage` Object, we need to be able to handle different message structures.

Just create a dictionary and **kwarg splatter them into the main code.

**Comment by Mahir-Sparkess** [comment]
* https://github.com/cedadev/asset-scanner/pull/28
* Added rabbit mq output:
* * takes data and optional kwargs for `x-delay`
* * publishes data, and creates properties with the header kwargs.
* Change rabbit mq input:
* * decode to just a dict instead of an ingest message. (does this break something else?)
* * message splatter to `process_file`. decoded message should have args like object_id, filepath, source_media.
